image: node:8.11.1

before_script:
   - npm install
 
stages:
   - pages
pages:
  stage: pages
  artifacts:
    paths:
       - dist
  script:
      - npm run build
  cache:
    paths:
       - node_modules
  only:
      - master
